#/appspec.yml
version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/build
hooks:
  BeforeInstall:
    - location: /beforeInstall.sh
      timeout: 120
      runas: root
  AfterInstall:
    - location: /afterInstall.sh
      timeout: 120
      runas: root