version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
      - echo $(basename ./target/*.war)
      - pwd
artifacts:
  files:
    - target/beethoven-0.0.1-SNAPSHOT.war
    - appspec.yml
    - cicd/**/*
  discard-paths: yes
cache:
  paths:
    - '/root/.m2/**/*'